name: CI/CD
run-name: CI/CD ${{github.event.pull_request.title}}

on:
  pull_request:
    types: [ opened, synchronize, closed ]

permissions:
  contents: write

jobs:
  Pre:
    if: github.event.pull_request.merged == false && (github.event.action == 'opened' || github.event.action == 'synchronize')
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yml@main
    with:
      pre_release: true

  Deploy_DEV:
    needs: Pre
    uses: HornaHomeLab/Actions_Deployments/.github/workflows/Run_docker_compose.yml@main
    with:
      environment: "development"
      version: ${{ needs.Pre.outputs.released_version }}
    secrets: inherit

  Full:
    if: github.event.pull_request.merged == true && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_create_release.yml@main
    with:
      pre_release: false
      latest: true

  Deploy_PRD:
    needs: Full
    uses: HornaHomeLab/Actions_Deployments/.github/workflows/Run_docker_compose.yml@main
    with:
      environment: "production"
      version: ${{ needs.Full.outputs.released_version }}
    secrets: inherit

  Remove:
    if: github.event.pull_request.merged == false && github.event.action == 'closed'
    uses: HornaHomeLab/Actions_Releases/.github/workflows/Process_remove_release.yml@main